<?php

namespace Database\Seeders;

use App\Models\Badge;
use Illuminate\Database\Seeder;

class BadgeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $badges = [
            // Content Creator (10 badges)
            [
                'slug' => 'anak-baru',
                'name' => 'Anak Baru',
                'description' => 'Buat catatan pertamamu',
                'icon' => 'sprout',
                'category' => 'content_creator',
                'tier' => 1,
                'requirement_type' => 'notes_created',
                'requirement_value' => 1,
            ],
            [
                'slug' => 'mau-rajin',
                'name' => 'Mau Rajin',
                'description' => 'Buat 5 catatan',
                'icon' => 'file-text',
                'category' => 'content_creator',
                'tier' => 1,
                'requirement_type' => 'notes_created',
                'requirement_value' => 5,
            ],
            [
                'slug' => 'lumayan-rajin',
                'name' => 'Lumayan Rajin',
                'description' => 'Buat 10 catatan',
                'icon' => 'pen-line',
                'category' => 'content_creator',
                'tier' => 2,
                'requirement_type' => 'notes_created',
                'requirement_value' => 10,
            ],
            [
                'slug' => 'rajin-beneran',
                'name' => 'Rajin Beneran',
                'description' => 'Buat 25 catatan',
                'icon' => 'pencil',
                'category' => 'content_creator',
                'tier' => 2,
                'requirement_type' => 'notes_created',
                'requirement_value' => 25,
            ],
            [
                'slug' => 'produktif-parah',
                'name' => 'Produktif Parah',
                'description' => 'Buat 50 catatan',
                'icon' => 'book-open',
                'category' => 'content_creator',
                'tier' => 3,
                'requirement_type' => 'notes_created',
                'requirement_value' => 50,
            ],
            [
                'slug' => 'sultan-notes',
                'name' => 'Sultan Notes',
                'description' => 'Buat 100 catatan',
                'icon' => 'book-marked',
                'category' => 'content_creator',
                'tier' => 4,
                'requirement_type' => 'notes_created',
                'requirement_value' => 100,
            ],
            [
                'slug' => 'gila-nulis',
                'name' => 'Gila Nulis',
                'description' => 'Buat 250 catatan',
                'icon' => 'crown',
                'category' => 'content_creator',
                'tier' => 5,
                'requirement_type' => 'notes_created',
                'requirement_value' => 250,
            ],
            [
                'slug' => 'dewa-catatan',
                'name' => 'Dewa Catatan',
                'description' => 'Buat 500 catatan',
                'icon' => 'star',
                'category' => 'content_creator',
                'tier' => 5,
                'requirement_type' => 'notes_created',
                'requirement_value' => 500,
            ],
            [
                'slug' => 'smart-notes',
                'name' => 'Smart Notes',
                'description' => 'Buat catatan dengan AI summary',
                'icon' => 'sparkles',
                'category' => 'content_creator',
                'tier' => 3,
                'requirement_type' => 'ai_summary_used',
                'requirement_value' => 1,
            ],
            [
                'slug' => 'multimedia-pro',
                'name' => 'Multimedia Pro',
                'description' => 'Upload 50 attachment',
                'icon' => 'image',
                'category' => 'content_creator',
                'tier' => 3,
                'requirement_type' => 'attachments_uploaded',
                'requirement_value' => 50,
            ],

            // Engagement - Likes Received (8 badges)
            [
                'slug' => 'ada-yang-suka',
                'name' => 'Ada yang Suka!',
                'description' => 'Dapat 1 like pertama',
                'icon' => 'thumbs-up',
                'category' => 'engagement',
                'tier' => 1,
                'requirement_type' => 'likes_received',
                'requirement_value' => 1,
            ],
            [
                'slug' => 'mulai-rame',
                'name' => 'Mulai Rame',
                'description' => 'Dapat 10 likes',
                'icon' => 'heart',
                'category' => 'engagement',
                'tier' => 2,
                'requirement_type' => 'likes_received',
                'requirement_value' => 10,
            ],
            [
                'slug' => 'rame-nih',
                'name' => 'Rame Nih',
                'description' => 'Dapat 50 likes',
                'icon' => 'trending-up',
                'category' => 'engagement',
                'tier' => 2,
                'requirement_type' => 'likes_received',
                'requirement_value' => 50,
            ],
            [
                'slug' => 'hits-banget',
                'name' => 'Hits Banget',
                'description' => 'Dapat 100 likes',
                'icon' => 'star',
                'category' => 'engagement',
                'tier' => 3,
                'requirement_type' => 'likes_received',
                'requirement_value' => 100,
            ],
            [
                'slug' => 'selebgram-kampus',
                'name' => 'Selebgram Kampus',
                'description' => 'Dapat 250 likes',
                'icon' => 'sparkles',
                'category' => 'engagement',
                'tier' => 4,
                'requirement_type' => 'likes_received',
                'requirement_value' => 250,
            ],
            [
                'slug' => 'sultan-likes',
                'name' => 'Sultan Likes',
                'description' => 'Dapat 500 likes',
                'icon' => 'crown',
                'category' => 'engagement',
                'tier' => 5,
                'requirement_type' => 'likes_received',
                'requirement_value' => 500,
            ],
            [
                'slug' => 'fyp',
                'name' => 'FYP!',
                'description' => 'Dapat 50 likes di 1 catatan',
                'icon' => 'flame',
                'category' => 'engagement',
                'tier' => 4,
                'requirement_type' => 'single_note_likes',
                'requirement_value' => 50,
            ],
            [
                'slug' => 'viral-parah',
                'name' => 'Viral Parah',
                'description' => 'Dapat 100 likes di 1 catatan',
                'icon' => 'zap',
                'category' => 'engagement',
                'tier' => 5,
                'requirement_type' => 'single_note_likes',
                'requirement_value' => 100,
            ],

            // Bookmarks Received (5 badges)
            [
                'slug' => 'worth-it',
                'name' => 'Worth It',
                'description' => 'Dapat 1 bookmark',
                'icon' => 'bookmark',
                'category' => 'bookmarks',
                'tier' => 1,
                'requirement_type' => 'bookmarks_received',
                'requirement_value' => 1,
            ],
            [
                'slug' => 'berguna-banget',
                'name' => 'Berguna Banget',
                'description' => 'Dapat 10 bookmarks',
                'icon' => 'bookmark-check',
                'category' => 'bookmarks',
                'tier' => 2,
                'requirement_type' => 'bookmarks_received',
                'requirement_value' => 10,
            ],
            [
                'slug' => 'penting-nih',
                'name' => 'Penting Nih',
                'description' => 'Dapat 25 bookmarks',
                'icon' => 'book-marked',
                'category' => 'bookmarks',
                'tier' => 3,
                'requirement_type' => 'bookmarks_received',
                'requirement_value' => 25,
            ],
            [
                'slug' => 'andalan-teman',
                'name' => 'Andalan Teman',
                'description' => 'Dapat 50 bookmarks',
                'icon' => 'library',
                'category' => 'bookmarks',
                'tier' => 3,
                'requirement_type' => 'bookmarks_received',
                'requirement_value' => 50,
            ],
            [
                'slug' => 'wajib-save',
                'name' => 'Wajib Save!',
                'description' => 'Dapat 100 bookmarks',
                'icon' => 'trophy',
                'category' => 'bookmarks',
                'tier' => 4,
                'requirement_type' => 'bookmarks_received',
                'requirement_value' => 100,
            ],

            // Community (7 badges)
            [
                'slug' => 'ikut-ngobrol',
                'name' => 'Ikut Ngobrol',
                'description' => 'Tulis komentar pertama',
                'icon' => 'message-circle',
                'category' => 'community',
                'tier' => 1,
                'requirement_type' => 'comments_written',
                'requirement_value' => 1,
            ],
            [
                'slug' => 'aktif-komen',
                'name' => 'Aktif Komen',
                'description' => 'Tulis 10 komentar',
                'icon' => 'messages-square',
                'category' => 'community',
                'tier' => 2,
                'requirement_type' => 'comments_written',
                'requirement_value' => 10,
            ],
            [
                'slug' => 'tukang-diskusi',
                'name' => 'Tukang Diskusi',
                'description' => 'Tulis 50 komentar',
                'icon' => 'users',
                'category' => 'community',
                'tier' => 2,
                'requirement_type' => 'comments_written',
                'requirement_value' => 50,
            ],
            [
                'slug' => 'rame-terus',
                'name' => 'Rame Terus',
                'description' => 'Tulis 100 komentar',
                'icon' => 'users-round',
                'category' => 'community',
                'tier' => 3,
                'requirement_type' => 'comments_written',
                'requirement_value' => 100,
            ],
            [
                'slug' => 'lord-of-comments',
                'name' => 'Lord of Comments',
                'description' => 'Tulis 250 komentar',
                'icon' => 'message-square-text',
                'category' => 'community',
                'tier' => 4,
                'requirement_type' => 'comments_written',
                'requirement_value' => 250,
            ],
            [
                'slug' => 'catatan-rame',
                'name' => 'Catatan Rame',
                'description' => 'Dapat 25 komentar',
                'icon' => 'message-square-more',
                'category' => 'community',
                'tier' => 3,
                'requirement_type' => 'comments_received',
                'requirement_value' => 25,
            ],
            [
                'slug' => 'hot-topic',
                'name' => 'Hot Topic!',
                'description' => 'Dapat 100 komentar',
                'icon' => 'flame',
                'category' => 'community',
                'tier' => 4,
                'requirement_type' => 'comments_received',
                'requirement_value' => 100,
            ],

            // Leaderboard (5 badges)
            [
                'slug' => 'masuk-list',
                'name' => 'Masuk List',
                'description' => 'Masuk top 50 global',
                'icon' => 'bar-chart-3',
                'category' => 'leaderboard',
                'tier' => 2,
                'requirement_type' => 'leaderboard_rank',
                'requirement_value' => 50,
            ],
            [
                'slug' => 'naik-kelas',
                'name' => 'Naik Kelas',
                'description' => 'Masuk top 20 global',
                'icon' => 'medal',
                'category' => 'leaderboard',
                'tier' => 3,
                'requirement_type' => 'leaderboard_rank',
                'requirement_value' => 20,
            ],
            [
                'slug' => 'top-banget',
                'name' => 'Top Banget',
                'description' => 'Masuk top 10 global',
                'icon' => 'award',
                'category' => 'leaderboard',
                'tier' => 4,
                'requirement_type' => 'leaderboard_rank',
                'requirement_value' => 10,
            ],
            [
                'slug' => 'hampir-juara',
                'name' => 'Hampir Juara',
                'description' => 'Masuk top 5 global',
                'icon' => 'trophy',
                'category' => 'leaderboard',
                'tier' => 4,
                'requirement_type' => 'leaderboard_rank',
                'requirement_value' => 5,
            ],
            [
                'slug' => 'yang-paling',
                'name' => 'Yang Paling!',
                'description' => 'Peringkat #1 global',
                'icon' => 'crown',
                'category' => 'leaderboard',
                'tier' => 5,
                'requirement_type' => 'leaderboard_rank',
                'requirement_value' => 1,
            ],

            // Streak (6 badges)
            [
                'slug' => 'seminggu-aja',
                'name' => 'Seminggu Aja',
                'description' => 'Streak 7 hari',
                'icon' => 'calendar-check',
                'category' => 'streak',
                'tier' => 1,
                'requirement_type' => 'streak_days',
                'requirement_value' => 7,
            ],
            [
                'slug' => 'dua-minggu',
                'name' => 'Dua Minggu!',
                'description' => 'Streak 14 hari',
                'icon' => 'calendar-days',
                'category' => 'streak',
                'tier' => 2,
                'requirement_type' => 'streak_days',
                'requirement_value' => 14,
            ],
            [
                'slug' => 'konsisten-sih',
                'name' => 'Konsisten Sih',
                'description' => 'Streak 30 hari',
                'icon' => 'target',
                'category' => 'streak',
                'tier' => 3,
                'requirement_type' => 'streak_days',
                'requirement_value' => 30,
            ],
            [
                'slug' => 'gak-ada-libur',
                'name' => 'Gak Ada Libur',
                'description' => 'Streak 60 hari',
                'icon' => 'rocket',
                'category' => 'streak',
                'tier' => 4,
                'requirement_type' => 'streak_days',
                'requirement_value' => 60,
            ],
            [
                'slug' => 'legend-streak',
                'name' => 'Legend!',
                'description' => 'Streak 100 hari',
                'icon' => 'flame',
                'category' => 'streak',
                'tier' => 5,
                'requirement_type' => 'streak_days',
                'requirement_value' => 100,
            ],
            [
                'slug' => 'touch-grass-kapan',
                'name' => 'Touch Grass Kapan?',
                'description' => 'Streak 365 hari',
                'icon' => 'infinity',
                'category' => 'streak',
                'tier' => 5,
                'requirement_type' => 'streak_days',
                'requirement_value' => 365,
            ],

            // University Pride (3 badges)
            [
                'slug' => 'hits-sekampus',
                'name' => 'Hits Sekampus',
                'description' => 'Top 10 di universitas',
                'icon' => 'building-2',
                'category' => 'university',
                'tier' => 3,
                'requirement_type' => 'university_rank',
                'requirement_value' => 10,
            ],
            [
                'slug' => 'jagoan-prodi',
                'name' => 'Jagoan Prodi',
                'description' => 'Top 5 di program studi',
                'icon' => 'book-open-check',
                'category' => 'university',
                'tier' => 3,
                'requirement_type' => 'program_study_rank',
                'requirement_value' => 5,
            ],
            [
                'slug' => 'jenius-lokal',
                'name' => 'Jenius Lokal',
                'description' => 'Top 3 di program studi',
                'icon' => 'graduation-cap',
                'category' => 'university',
                'tier' => 4,
                'requirement_type' => 'program_study_rank',
                'requirement_value' => 3,
            ],

            // Special (2 badges)
            [
                'slug' => 'early-adopter',
                'name' => 'Early Adopter',
                'description' => 'Gabung di bulan pertama',
                'icon' => 'rocket',
                'category' => 'special',
                'tier' => 3,
                'requirement_type' => 'early_adopter',
                'requirement_value' => 1,
            ],
            [
                'slug' => 'helpful-banget',
                'name' => 'Helpful Banget',
                'description' => 'Dapat 100 total engagement',
                'icon' => 'heart-handshake',
                'category' => 'special',
                'tier' => 4,
                'requirement_type' => 'total_engagement',
                'requirement_value' => 100,
            ],
        ];

        foreach ($badges as $badge) {
            Badge::updateOrCreate(
                ['slug' => $badge['slug']],
                $badge
            );
        }
    }
}
