<?php

namespace Database\Seeders;

use App\Models\ProgramStudy;
use App\Models\University;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        $universities = [
            [
                'nama' => 'Universitas Indonesia',
                'singkatan' => 'UI',
                'kota' => 'Depok',
                'domain' => 'ui.ac.id',
                'domain_aliases' => ['student.ui.ac.id'],
                'programs' => [
                    ['nama' => 'Teknik Informatika', 'jenjang' => 'S1'],
                    ['nama' => 'Sistem Informasi', 'jenjang' => 'S1'],
                    ['nama' => 'Kedokteran', 'jenjang' => 'S1'],
                    ['nama' => 'Farmasi', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Hukum', 'jenjang' => 'S1'],
                    ['nama' => 'Psikologi', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Sipil', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Elektro', 'jenjang' => 'S1'],
                    ['nama' => 'Arsitektur', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Komunikasi', 'jenjang' => 'S1'],
                    ['nama' => 'Akuntansi', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Politik', 'jenjang' => 'S1'],
                    ['nama' => 'Sastra Inggris', 'jenjang' => 'S1'],
                    ['nama' => 'Matematika', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Institut Teknologi Bandung',
                'singkatan' => 'ITB',
                'kota' => 'Bandung',
                'domain' => 'itb.ac.id',
                'domain_aliases' => ['students.itb.ac.id'],
                'programs' => [
                    ['nama' => 'Teknik Informatika', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Elektro', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Mesin', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Kimia', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Sipil', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Industri', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Lingkungan', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Kelautan', 'jenjang' => 'S1'],
                    ['nama' => 'Arsitektur', 'jenjang' => 'S1'],
                    ['nama' => 'Perencanaan Wilayah dan Kota', 'jenjang' => 'S1'],
                    ['nama' => 'Matematika', 'jenjang' => 'S1'],
                    ['nama' => 'Fisika', 'jenjang' => 'S1'],
                    ['nama' => 'Kimia', 'jenjang' => 'S1'],
                    ['nama' => 'Biologi', 'jenjang' => 'S1'],
                    ['nama' => 'Desain Komunikasi Visual', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Universitas Gadjah Mada',
                'singkatan' => 'UGM',
                'kota' => 'Yogyakarta',
                'domain' => 'ugm.ac.id',
                'domain_aliases' => ['mail.ugm.ac.id'],
                'programs' => [
                    ['nama' => 'Teknologi Informasi', 'jenjang' => 'S1'],
                    ['nama' => 'Sistem Informasi', 'jenjang' => 'S1'],
                    ['nama' => 'Kedokteran', 'jenjang' => 'S1'],
                    ['nama' => 'Kedokteran Gigi', 'jenjang' => 'S1'],
                    ['nama' => 'Farmasi', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Gizi', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Hukum', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Politik', 'jenjang' => 'S1'],
                    ['nama' => 'Psikologi', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Sipil', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Elektro', 'jenjang' => 'S1'],
                    ['nama' => 'Arsitektur', 'jenjang' => 'S1'],
                    ['nama' => 'Ekonomi Pembangunan', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                    ['nama' => 'Agribisnis', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Institut Pertanian Bogor',
                'singkatan' => 'IPB',
                'kota' => 'Bogor',
                'domain' => 'ipb.ac.id',
                'domain_aliases' => ['apps.ipb.ac.id'],
                'programs' => [
                    ['nama' => 'Agribisnis', 'jenjang' => 'S1'],
                    ['nama' => 'Agroteknologi', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Tanah', 'jenjang' => 'S1'],
                    ['nama' => 'Teknologi Pangan', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Gizi', 'jenjang' => 'S1'],
                    ['nama' => 'Bioteknologi', 'jenjang' => 'S1'],
                    ['nama' => 'Kehutanan', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen Sumberdaya Perairan', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Kelautan', 'jenjang' => 'S1'],
                    ['nama' => 'Statistika', 'jenjang' => 'S1'],
                    ['nama' => 'Matematika', 'jenjang' => 'S1'],
                    ['nama' => 'Ekonomi Pembangunan', 'jenjang' => 'S1'],
                    ['nama' => 'Kedokteran Hewan', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Industri Pertanian', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Institut Teknologi Sepuluh Nopember',
                'singkatan' => 'ITS',
                'kota' => 'Surabaya',
                'domain' => 'its.ac.id',
                'domain_aliases' => ['students.its.ac.id'],
                'programs' => [
                    ['nama' => 'Teknik Informatika', 'jenjang' => 'S1'],
                    ['nama' => 'Sistem Informasi', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Elektro', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Mesin', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Kimia', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Sipil', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Industri', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Material', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Kelautan', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Fisika', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Lingkungan', 'jenjang' => 'S1'],
                    ['nama' => 'Perencanaan Wilayah dan Kota', 'jenjang' => 'S1'],
                    ['nama' => 'Desain Produk', 'jenjang' => 'S1'],
                    ['nama' => 'Matematika', 'jenjang' => 'S1'],
                    ['nama' => 'Statistika', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Universitas Airlangga',
                'singkatan' => 'UNAIR',
                'kota' => 'Surabaya',
                'domain' => 'unair.ac.id',
                'domain_aliases' => ['student.unair.ac.id'],
                'programs' => [
                    ['nama' => 'Kedokteran', 'jenjang' => 'S1'],
                    ['nama' => 'Kedokteran Gigi', 'jenjang' => 'S1'],
                    ['nama' => 'Farmasi', 'jenjang' => 'S1'],
                    ['nama' => 'Keperawatan', 'jenjang' => 'S1'],
                    ['nama' => 'Kesehatan Masyarakat', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Komunikasi', 'jenjang' => 'S1'],
                    ['nama' => 'Psikologi', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Hukum', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                    ['nama' => 'Akuntansi', 'jenjang' => 'S1'],
                    ['nama' => 'Sistem Informasi', 'jenjang' => 'S1'],
                    ['nama' => 'Hubungan Internasional', 'jenjang' => 'S1'],
                    ['nama' => 'Sastra Inggris', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Lingkungan', 'jenjang' => 'S1'],
                    ['nama' => 'Ekonomi Islam', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Universitas Diponegoro',
                'singkatan' => 'UNDIP',
                'kota' => 'Semarang',
                'domain' => 'undip.ac.id',
                'domain_aliases' => ['students.undip.ac.id'],
                'programs' => [
                    ['nama' => 'Teknik Mesin', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Sipil', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Elektro', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Industri', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Kimia', 'jenjang' => 'S1'],
                    ['nama' => 'Perencanaan Wilayah dan Kota', 'jenjang' => 'S1'],
                    ['nama' => 'Sistem Informasi', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Informatika', 'jenjang' => 'S1'],
                    ['nama' => 'Kedokteran', 'jenjang' => 'S1'],
                    ['nama' => 'Keperawatan', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Hukum', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Komunikasi', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                    ['nama' => 'Akuntansi', 'jenjang' => 'S1'],
                    ['nama' => 'Hubungan Internasional', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Universitas Brawijaya',
                'singkatan' => 'UB',
                'kota' => 'Malang',
                'domain' => 'ub.ac.id',
                'domain_aliases' => ['student.ub.ac.id'],
                'programs' => [
                    ['nama' => 'Kedokteran', 'jenjang' => 'S1'],
                    ['nama' => 'Kedokteran Hewan', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Hukum', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Administrasi Negara', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                    ['nama' => 'Akuntansi', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Pengairan', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Sipil', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Mesin', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Elektro', 'jenjang' => 'S1'],
                    ['nama' => 'Sistem Informasi', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Informatika', 'jenjang' => 'S1'],
                    ['nama' => 'Psikologi', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Komunikasi', 'jenjang' => 'S1'],
                    ['nama' => 'Agribisnis', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Universitas Sebelas Maret',
                'singkatan' => 'UNS',
                'kota' => 'Surakarta',
                'domain' => 'uns.ac.id',
                'domain_aliases' => ['student.uns.ac.id'],
                'programs' => [
                    ['nama' => 'Pendidikan Dokter', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Kimia', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Sipil', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Industri', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Mesin', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Informatika', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Matematika', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Bahasa Inggris', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Guru Sekolah Dasar', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Hukum', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                    ['nama' => 'Akuntansi', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Komunikasi', 'jenjang' => 'S1'],
                    ['nama' => 'Psikologi', 'jenjang' => 'S1'],
                    ['nama' => 'Agribisnis', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Universitas Telkom',
                'singkatan' => 'TEL-U',
                'kota' => 'Bandung',
                'domain' => 'telkomuniversity.ac.id',
                'domain_aliases' => ['student.telkomuniversity.ac.id'],
                'programs' => [
                    ['nama' => 'Teknik Telekomunikasi', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Informatika', 'jenjang' => 'S1'],
                    ['nama' => 'Sistem Informasi', 'jenjang' => 'S1'],
                    ['nama' => 'Rekayasa Perangkat Lunak', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Elektro', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Industri', 'jenjang' => 'S1'],
                    ['nama' => 'Data Science', 'jenjang' => 'S1'],
                    ['nama' => 'Desain Komunikasi Visual', 'jenjang' => 'S1'],
                    ['nama' => 'Desain Produk', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Komunikasi', 'jenjang' => 'S1'],
                    ['nama' => 'Hubungan Masyarakat', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                    ['nama' => 'Akuntansi', 'jenjang' => 'S1'],
                    ['nama' => 'Bisnis Digital', 'jenjang' => 'S1'],
                    ['nama' => 'Multimedia Kreatif', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Universitas Negeri Surabaya',
                'singkatan' => 'UNESA',
                'kota' => 'Surabaya',
                'domain' => 'unesa.ac.id',
                'domain_aliases' => ['mhs.unesa.ac.id'],
                'programs' => [
                    ['nama' => 'Pendidikan Matematika', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Fisika', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Kimia', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Biologi', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Bahasa Inggris', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Bahasa Indonesia', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Guru Sekolah Dasar', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Anak Usia Dini', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Seni Rupa', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Jasmani', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Teknologi Informasi', 'jenjang' => 'S1'],
                    ['nama' => 'Sistem Informasi', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Informatika', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Sipil', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Elektro', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Mesin', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Universitas Padjadjaran',
                'singkatan' => 'UNPAD',
                'kota' => 'Bandung',
                'domain' => 'unpad.ac.id',
                'domain_aliases' => ['student.unpad.ac.id'],
                'programs' => [
                    ['nama' => 'Kedokteran', 'jenjang' => 'S1'],
                    ['nama' => 'Kedokteran Gigi', 'jenjang' => 'S1'],
                    ['nama' => 'Farmasi', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Hukum', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Komunikasi', 'jenjang' => 'S1'],
                    ['nama' => 'Hubungan Internasional', 'jenjang' => 'S1'],
                    ['nama' => 'Administrasi Publik', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                    ['nama' => 'Akuntansi', 'jenjang' => 'S1'],
                    ['nama' => 'Ekonomi Pembangunan', 'jenjang' => 'S1'],
                    ['nama' => 'Psikologi', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Informatika', 'jenjang' => 'S1'],
                    ['nama' => 'Statistika', 'jenjang' => 'S1'],
                    ['nama' => 'Agribisnis', 'jenjang' => 'S1'],
                    ['nama' => 'Biologi', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Universitas Hasanuddin',
                'singkatan' => 'UNHAS',
                'kota' => 'Makassar',
                'domain' => 'unhas.ac.id',
                'domain_aliases' => ['student.unhas.ac.id'],
                'programs' => [
                    ['nama' => 'Kedokteran', 'jenjang' => 'S1'],
                    ['nama' => 'Kedokteran Gigi', 'jenjang' => 'S1'],
                    ['nama' => 'Keperawatan', 'jenjang' => 'S1'],
                    ['nama' => 'Kesehatan Masyarakat', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Kelautan', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Sipil', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Mesin', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Industri', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Geologi', 'jenjang' => 'S1'],
                    ['nama' => 'Agribisnis', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Kelautan', 'jenjang' => 'S1'],
                    ['nama' => 'Perikanan', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Hukum', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                    ['nama' => 'Sistem Informasi', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Universitas Andalas',
                'singkatan' => 'UNAND',
                'kota' => 'Padang',
                'domain' => 'unand.ac.id',
                'domain_aliases' => ['student.unand.ac.id'],
                'programs' => [
                    ['nama' => 'Kedokteran', 'jenjang' => 'S1'],
                    ['nama' => 'Farmasi', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Keperawatan', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Pertanian', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Sipil', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Mesin', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Elektro', 'jenjang' => 'S1'],
                    ['nama' => 'Sistem Informasi', 'jenjang' => 'S1'],
                    ['nama' => 'Teknik Informatika', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Hukum', 'jenjang' => 'S1'],
                    ['nama' => 'Ilmu Politik', 'jenjang' => 'S1'],
                    ['nama' => 'Sosiologi', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                    ['nama' => 'Akuntansi', 'jenjang' => 'S1'],
                    ['nama' => 'Agribisnis', 'jenjang' => 'S1'],
                ],
            ],
            [
                'nama' => 'Universitas Pendidikan Indonesia',
                'singkatan' => 'UPI',
                'kota' => 'Bandung',
                'domain' => 'upi.edu',
                'domain_aliases' => ['student.upi.edu'],
                'programs' => [
                    ['nama' => 'Pendidikan Guru Sekolah Dasar', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Guru PAUD', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Matematika', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Fisika', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Kimia', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Biologi', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Bahasa Indonesia', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Bahasa Inggris', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Seni Musik', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Seni Rupa', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Jasmani', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Teknik Mesin', 'jenjang' => 'S1'],
                    ['nama' => 'Pendidikan Teknik Elektro', 'jenjang' => 'S1'],
                    ['nama' => 'Manajemen', 'jenjang' => 'S1'],
                    ['nama' => 'Psikologi', 'jenjang' => 'S1'],
                ],
            ],
        ];

        foreach ($universities as $data) {
            $programs = $data['programs'] ?? [];
            $universityAttributes = [
                'slug' => Str::slug($data['nama']),
                'domain' => $data['domain'],
                'domain_aliases' => $data['domain_aliases'],
                'singkatan' => $data['singkatan'] ?? null,
                'kota' => $data['kota'] ?? null,
                'aktif' => 'true',
            ];

            /** @var University $university */
            $university = University::updateOrCreate(
                ['domain' => $data['domain']],
                array_merge(
                    [
                        'nama' => $data['nama'],
                    ],
                    $universityAttributes
                )
            );

            foreach ($programs as $program) {
                ProgramStudy::updateOrCreate(
                    [
                        'university_id' => $university->id,
                        'slug' => Str::slug($program['nama']),
                    ],
                    [
                        'nama' => $program['nama'],
                        'slug' => Str::slug($program['nama']),
                        'jenjang' => $program['jenjang'] ?? null,
                        'aktif' => 'true',
                    ]
                );
            }
        }

        $defaultProgram = ProgramStudy::query()->first();

        if ($defaultProgram) {
            User::firstOrCreate(
                ['email' => 'test@' . $defaultProgram->university->domain],
                [
                    'name' => 'Test Mahasiswa',
                    'password' => 'password',
                    'email_verified_at' => now(),
                    'university_id' => $defaultProgram->university_id,
                    'program_study_id' => $defaultProgram->id,
                    'cohort_year' => '2021',
                    'profile_completed' => 'true',
                    'profile_completed_at' => now(),
                ]
            );
        }
    }
}
